"use client";

import { useState, useRef } from "react";
import SignatureCanvas from "react-signature-canvas";

const CONTRACT_PAGE_1 = `SERVICE AND REVENUE SHARING AGREEMENT

--------------------------------------------------

Article 1 – Contracting Parties

This agreement is entered into between:

Muhammed Rizwan Iqbal, citizen of ____________, with identification number ____________, residing at ____________, representative of the company "RINS.AI LLC", operator of the "RINS.AI" application (hereinafter referred to as the "Client")

and

Convex SHPK, a legal entity registered under the applicable laws of the Republic of Kosovo, represented by Erion Ahmeti (hereinafter referred to as the "Service Provider")

The Client and the Service Provider shall hereinafter be collectively referred to as the "Parties".

--------------------------------------------------

Article 2 – Acceptance of the Agreement

This agreement is considered accepted and enters into force upon electronic signature by the Client.

--------------------------------------------------

Article 3 – Purpose

The purpose of this agreement is the provision of services including:

– lead generation
– marketing and outreach
– growth and scaling strategy

with the objective of increasing customers and revenue for the "RINS.AI" application.

--------------------------------------------------

Article 4 – Services

The Service Provider agrees to provide:

– generation of potential clients (leads)
– sales strategy development
– optimization of conversion processes
– operational and advisory support

Weekly reporting by the Service Provider includes:
(a) number of prospects contacted,
(b) contact channel,
(c) status of each prospect,
(d) scheduled and completed meetings,
(e) qualified leads,
(f) converted clients,
(g) main reasons for rejection,
(h) market feedback and operational recommendations.

A "lead" is defined as a business client who becomes a paying subscriber. The minimum number of prospects contacted is 50+ per month.

The Service Provider does not guarantee fixed numerical results.

--------------------------------------------------

Article 5 – Client Obligations

The Client agrees to:

– actively cooperate
– not obstruct the sales process
– accurately report every client generated by the Service Provider
– not conceal revenue or agreements

--------------------------------------------------

Article 6 – Payments

The Client agrees to:

– a fixed payment of **€120 per month**
– a payment of **30% of revenue from each client closed by the Service Provider**, for **12 months** from the client's first payment

Payments:

– are made at the end of each calendar month
– must be completed within **5 days** after the end of the month

--------------------------------------------------

Article 7 – Penalties

In case of late payment:

– a penalty of **5% per week** is applied on the unpaid amount
– the Service Provider has the right to immediately suspend services

--------------------------------------------------

Article 8 – Ownership of Leads

All leads and clients generated by the Service Provider are considered the commercial property of the Service Provider for financial purposes.

The Client agrees that:

– they may not bypass the Service Provider in dealings with these clients
– all revenue from such clients is automatically subject to the **30% payment**

This right remains valid for **24 months after termination of the collaboration**.

In case of violation:

– the Client must pay **100% of the value of the contract with the respective client**
– plus any financial and legal damages

--------------------------------------------------

Article 9 – Transparency and Audit

The Service Provider has the right to request verification of:

– communications with clients
– contracts
– payments

The Client is obligated to fully cooperate.

--------------------------------------------------

Article 10 – Confidentiality

The Parties agree to maintain confidentiality regarding:

– strategies
– clients
– business data

This obligation continues for **2 years after termination of the agreement**.

--------------------------------------------------

Article 11 – Non-Competition

The Client may not engage third parties for similar services without written approval from the Service Provider during the term of this agreement.`;

const CONTRACT_PAGE_2 = `--------------------------------------------------

Article 12 – Duration

This agreement is valid for an indefinite period.

--------------------------------------------------

Article 13 – Termination

Either party may terminate the agreement with **30 days prior notice**.

The Service Provider's rights over generated clients remain valid after termination.

In the event of the closure of RINS.AI LLC, this agreement terminates automatically and any financial obligations of the Client toward the Service Provider are extinguished.

--------------------------------------------------

Article 14 – Force Majeure

Neither party is liable for non-performance due to:

– natural disasters
– war
– government decisions

--------------------------------------------------

Article 15 – Jurisdiction

Any dispute shall first be resolved amicably.

In case of failure:
– the competent jurisdiction is the **Basic Court in Pristina, Republic of Kosovo**

--------------------------------------------------

Article 16 – Final Provisions

– This agreement constitutes the entire agreement between the Parties
– Any amendments must be made in writing
– If any provision is invalid, the remainder remains in force

--------------------------------------------------

Acceptance

By accepting this agreement electronically, the Client declares that:

– they have fully read and understood it
– they agree to all terms
– they accept its financial and legal obligations

--------------------------------------------------

APPENDICES

--------------------------------------------------

APPENDIX A – TRANSPARENCY AND COOPERATION FRAMEWORK

--------------------------------------------------

Article A1 – Revenue Transparency

The Client undertakes to accurately and fully declare all revenue generated from clients provided by the Service Provider.

In case of discrepancies:

– financial obligations toward the Service Provider remain fully payable
– the parties agree to resolve the situation transparently and professionally
– in case of proven damage, proportional compensation may be required

--------------------------------------------------

Article A2 – Payment Obligation

The obligation to pay arises automatically when revenue is generated from clients provided by the Service Provider.

Payment is considered a direct contractual obligation and does not require additional procedures to be activated.

--------------------------------------------------

Article A3 – Verification and Cooperation

The Service Provider has the right to request reasonable verification regarding:

– generated clients
– related revenues
– relevant operational information

The Client agrees to cooperate openly and in a timely manner.

--------------------------------------------------

Article A4 – Fair Cooperation (Non-Circumvention)

The Parties agree to act in good faith and not to bypass one another regarding clients, contacts, or opportunities created during the collaboration.

Any such cooperation remains subject to the financial terms of this agreement.

--------------------------------------------------

Article A5 – Validity of Generated Clients

Any client generated during the collaboration is considered part of the contractual relationship between the Parties.

The rights and financial obligations arising from such clients continue to apply after termination of the collaboration for a reasonable period.

--------------------------------------------------

Article A6 – Termination for Just Cause

The Service Provider has the right to terminate the agreement in cases of:

– lack of cooperation
– repeated payment delays
– significant reporting discrepancies

Termination is carried out professionally and with prior notice when possible.

--------------------------------------------------

Article A7 – Costs and Liability

In case of disputes, the Parties agree to first resolve the matter amicably.

If legal intervention is required, costs may be allocated according to the final decision of the competent authority.

--------------------------------------------------

Article A8 – Enforceability

This agreement and its appendices may be formalized through notarization, increasing legal security and enforceability.

--------------------------------------------------

Article A9 – Priority of the Appendix

This appendix serves to clarify and support the main agreement.

In case of ambiguity, interpretation shall be made in accordance with the spirit of cooperation and the main agreement.

--------------------------------------------------

APPENDIX B – PERSONAL UNDERTAKING

--------------------------------------------------

Article B1 – Personal Commitment

The Client declares that they assume personal responsibility for fulfilling the obligations of this agreement.

--------------------------------------------------

Article B2 – Fulfillment of Obligations

In case of non-performance by the business structure, the obligations remain valid and enforceable against the responsible individual.

--------------------------------------------------

Article B3 – Nature of Commitment

This commitment is an integral part of the agreement and aims to ensure stable and trustworthy cooperation between the Parties.

--------------------------------------------------

Article B4 – Legal Force

This commitment has the same legal force as the main agreement and is enforced in accordance with applicable law.

--------------------------------------------------

Article B5 – Continuity

This commitment remains in force until full fulfillment of all obligations arising from this agreement.

--------------------------------------------------

Acceptance

By accepting this agreement, the Client confirms that:

– they have read and understood the terms
– they agree to them
– they commit to fair and transparent cooperation

--------------------------------------------------

SIGNATURES

For Convex SHPK
Erion Ahmeti
Signature: _______________________
Date: _______________________

For RINS.AI LLC (Client)
Muhammed Rizwan Iqbal
Signature: _______________________
Date: _______________________`;

export default function Home() {
  const [step, setStep] = useState<"contract" | "signatures" | "success">("contract");
  const [currentPage, setCurrentPage] = useState<1 | 2>(1);
  const [nuraName, setNuraName] = useState("");
  const [nuraPersonalName, setNuraPersonalName] = useState("");
  const [nuraPersonalId, setNuraPersonalId] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const nuraSigRef = useRef<SignatureCanvas>(null);
  const nuraPersonalSigRef = useRef<SignatureCanvas>(null);

  const handleAcceptContract = () => {
    setStep("signatures");
  };

  const handleSubmit = async () => {
    if (!nuraSigRef.current || !nuraPersonalSigRef.current) return;
    
    if (nuraSigRef.current.isEmpty() || nuraPersonalSigRef.current.isEmpty()) {
      alert("Please complete both signatures!");
      return;
    }

    if (!nuraName.trim() || !nuraPersonalName.trim() || !nuraPersonalId.trim()) {
      alert("Please complete all required fields!");
      return;
    }

    setIsSubmitting(true);

    try {
      const nuraSignature = nuraSigRef.current.toDataURL();
      const nuraPersonalSignature = nuraPersonalSigRef.current.toDataURL();

      // Send signatures to backend
      const response = await fetch('/api/send-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          convexSignature: nuraSignature,
          nuraSignature: nuraPersonalSignature,
          convexName: nuraName.trim(),
          nuraName: nuraPersonalName.trim(),
          nuraPersonalId: nuraPersonalId.trim(),
          signedAt: new Date().toISOString(),
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to process contract');
      }

      const result = await response.json();
      
      setStep("success");
    } catch (error) {
      console.error("Error:", error);
      alert("Ndodhi një gabim gjatë dërgimit të email-it. Ju lutem provoni përsëri.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto">
        {step === "contract" && (
          <div className="bg-white rounded-lg shadow-2xl p-8 md:p-12 border-t-4 border-blue-600 transition-all duration-300">
            <div className="text-center mb-10">
              <div className="inline-block mb-6">
                <div className="flex items-center justify-center gap-3 bg-blue-600 text-white px-8 py-3 rounded-md text-sm font-bold uppercase tracking-wider shadow-lg">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  Official Contract
                </div>
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-slate-800 mb-3 tracking-tight">
                Service Agreement
              </h1>
              <p className="text-xl text-slate-600 font-semibold">Convex SHPK × RINS.AI LLC</p>
              <div className="mt-4 flex items-center justify-center gap-2 text-sm text-slate-500 font-medium">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                {new Date().toLocaleDateString('sq-AL', { year: 'numeric', month: 'long', day: 'numeric' })}
              </div>
            </div>

            <div className="mb-8 flex flex-wrap justify-center gap-3">
              <button
                onClick={() => setCurrentPage(1)}
                className={`px-8 py-3 rounded-md font-bold uppercase tracking-wide transition-all duration-200 ${
                  currentPage === 1
                    ? "bg-blue-600 text-white shadow-lg"
                    : "bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-300"
                }`}
              >
                <div className="flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Page 1 - Main Agreement
                </div>
              </button>
              <button
                onClick={() => setCurrentPage(2)}
                className={`px-8 py-3 rounded-md font-bold uppercase tracking-wide transition-all duration-200 ${
                  currentPage === 2
                    ? "bg-blue-600 text-white shadow-lg"
                    : "bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-300"
                }`}
              >
                <div className="flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
                  </svg>
                  Page 2 - Appendices
                </div>
              </button>
            </div>

            <div className="mb-8">
              <div className="bg-slate-50 rounded-lg p-8 max-h-[500px] overflow-y-auto border-2 border-slate-200 shadow-inner">
                <pre className="whitespace-pre-wrap text-sm text-slate-800 font-sans leading-relaxed">
                  {currentPage === 1 ? CONTRACT_PAGE_1 : CONTRACT_PAGE_2}
                </pre>
              </div>
            </div>

            <div className="flex flex-wrap justify-center gap-4">
              {currentPage === 1 && (
                <button
                  onClick={() => setCurrentPage(2)}
                  className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold py-4 px-8 rounded-md transition-all duration-200 border border-slate-300 shadow-md uppercase tracking-wide"
                >
                  <div className="flex items-center gap-2">
                    View Page 2
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                    </svg>
                  </div>
                </button>
              )}
              {currentPage === 2 && (
                <button
                  onClick={() => setCurrentPage(1)}
                  className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold py-4 px-8 rounded-md transition-all duration-200 border border-slate-300 shadow-md uppercase tracking-wide"
                >
                  <div className="flex items-center gap-2">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 17l-5-5m0 0l5-5m-5 5h12" />
                    </svg>
                    Back to Page 1
                  </div>
                </button>
              )}
              <button
                onClick={handleAcceptContract}
                className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 px-10 rounded-md shadow-xl hover:shadow-2xl transition-all duration-200 uppercase tracking-wide"
              >
                <div className="flex items-center gap-2">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                  Accept & Sign Contract
                </div>
              </button>
            </div>
          </div>
        )}

        {step === "signatures" && (
          <div className="bg-white rounded-lg shadow-2xl p-8 md:p-12 border-t-4 border-blue-600 transition-all duration-300">
            <div className="text-center mb-10">
              <div className="inline-block mb-6">
                <div className="flex items-center justify-center gap-3 bg-blue-600 text-white px-8 py-3 rounded-md text-sm font-bold uppercase tracking-wider shadow-lg">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                  Step 2 of 2
                </div>
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-slate-800 mb-3 tracking-tight">
                Contract Signature
              </h1>
              <p className="text-lg text-slate-600 font-medium">Please complete the information and sign below</p>
            </div>

            <div className="space-y-8">
              <div className="bg-slate-50 rounded-lg p-8 border-2 border-slate-200">
                <div className="flex items-center gap-3 mb-6">
                  <div className="bg-blue-600 text-white w-12 h-12 rounded-md flex items-center justify-center font-bold shadow-lg text-xl">
                    1
                  </div>
                  <h3 className="text-2xl font-bold text-slate-800 uppercase tracking-wide">RINS.AI LLC (Client)</h3>
                </div>
                <label className="block text-sm font-bold text-slate-700 mb-3 uppercase tracking-wide">
                  Client Name
                </label>
                <input
                  type="text"
                  value={nuraName}
                  onChange={(e) => setNuraName(e.target.value)}
                  placeholder="Muhammed Rizwan Iqbal"
                  className="w-full px-5 py-3 border-2 border-slate-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all bg-white shadow-sm text-lg"
                />
                <label className="block text-sm font-bold text-slate-700 mt-6 mb-3 uppercase tracking-wide">
                  Electronic Signature
                </label>
                <div className="border-2 border-slate-300 rounded-md bg-white shadow-md overflow-hidden">
                  <SignatureCanvas
                    ref={nuraSigRef}
                    canvasProps={{
                      className: "w-full h-48",
                    }}
                  />
                </div>
                <button
                  onClick={() => nuraSigRef.current?.clear()}
                  className="mt-3 flex items-center gap-2 text-sm text-blue-600 hover:text-blue-800 font-bold transition-colors uppercase tracking-wide"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Clear Signature
                </button>
              </div>

              <div className="bg-amber-50 rounded-lg p-8 border-2 border-amber-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="bg-amber-600 text-white w-12 h-12 rounded-md flex items-center justify-center font-bold shadow-lg text-xl">
                    2
                  </div>
                  <div>
                    <h3 className="text-2xl font-bold text-slate-800 uppercase tracking-wide">Personal Guarantee</h3>
                    <p className="text-sm text-amber-700 font-semibold mt-1">Muhammed Rizwan Iqbal - Individual</p>
                  </div>
                </div>
                <label className="block text-sm font-bold text-slate-700 mb-3 uppercase tracking-wide">
                  Full Name (Individual)
                </label>
                <input
                  type="text"
                  value={nuraPersonalName}
                  onChange={(e) => setNuraPersonalName(e.target.value)}
                  placeholder="Muhammed Rizwan Iqbal"
                  className="w-full px-5 py-3 border-2 border-amber-300 rounded-md focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition-all bg-white shadow-sm text-lg"
                />
                <label className="block text-sm font-bold text-slate-700 mt-6 mb-3 uppercase tracking-wide">
                  Personal ID Number
                </label>
                <input
                  type="text"
                  value={nuraPersonalId}
                  onChange={(e) => setNuraPersonalId(e.target.value)}
                  placeholder="ID Number / Passport Number"
                  className="w-full px-5 py-3 border-2 border-amber-300 rounded-md focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition-all bg-white shadow-sm text-lg"
                />
                <label className="block text-sm font-bold text-slate-700 mt-6 mb-3 uppercase tracking-wide">
                  Personal Signature (Appendix B)
                </label>
                <div className="border-2 border-amber-300 rounded-md bg-white shadow-md overflow-hidden">
                  <SignatureCanvas
                    ref={nuraPersonalSigRef}
                    canvasProps={{
                      className: "w-full h-48",
                    }}
                  />
                </div>
                <button
                  onClick={() => nuraPersonalSigRef.current?.clear()}
                  className="mt-3 flex items-center gap-2 text-sm text-amber-700 hover:text-amber-900 font-bold transition-colors uppercase tracking-wide"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Clear Signature
                </button>
              </div>
            </div>

            <div className="mt-10 flex flex-wrap justify-center gap-4">
              <button
                onClick={() => setStep("contract")}
                className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold py-4 px-8 rounded-md transition-all duration-200 border border-slate-300 shadow-md uppercase tracking-wide"
              >
                <div className="flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 17l-5-5m0 0l5-5m-5 5h12" />
                  </svg>
                  Go Back
                </div>
              </button>
              <button
                onClick={handleSubmit}
                disabled={isSubmitting}
                className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-400 text-white font-bold py-4 px-10 rounded-md shadow-xl hover:shadow-2xl transition-all duration-200 disabled:cursor-not-allowed uppercase tracking-wide"
              >
                <div className="flex items-center gap-2">
                  {isSubmitting ? (
                    <>
                      <svg className="animate-spin w-6 h-6" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Submitting...
                    </>
                  ) : (
                    <>
                      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      Sign & Submit Contract
                    </>
                  )}
                </div>
              </button>
            </div>
          </div>
        )}

        {step === "success" && (
          <div className="bg-white rounded-lg shadow-2xl p-8 md:p-12 border-t-4 border-blue-600 transition-all duration-300">
            <div className="text-center">
              <div className="mb-8 relative">
                <div className="relative inline-block">
                  <div className="bg-blue-600 w-24 h-24 rounded-full flex items-center justify-center shadow-2xl">
                    <svg
                      className="w-14 h-14 text-white"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={3}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                  </div>
                </div>
              </div>
              
              <div className="mb-6">
                <div className="inline-block mb-6">
                  <div className="flex items-center justify-center gap-3 bg-blue-600 text-white px-8 py-3 rounded-md text-sm font-bold uppercase tracking-wider shadow-lg">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Completed
                  </div>
                </div>
                <h1 className="text-4xl md:text-5xl font-bold text-slate-800 mb-4 tracking-tight">
                  Contract Successfully Signed!
                </h1>
                <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto">
                  The contract has been saved in the system and automatically sent to the specified email addresses.
                </p>
              </div>

              <div className="bg-slate-50 rounded-lg p-6 mb-8 border-2 border-slate-200">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
                  <div className="flex flex-col items-center gap-2">
                    <div className="bg-blue-600 w-12 h-12 rounded-md flex items-center justify-center shadow-md">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <p className="text-sm font-bold text-slate-700 uppercase tracking-wide">Signed</p>
                  </div>
                  <div className="flex flex-col items-center gap-2">
                    <div className="bg-blue-600 w-12 h-12 rounded-md flex items-center justify-center shadow-md">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                    </div>
                    <p className="text-sm font-bold text-slate-700 uppercase tracking-wide">Saved</p>
                  </div>
                  <div className="flex flex-col items-center gap-2">
                    <div className="bg-blue-600 w-12 h-12 rounded-md flex items-center justify-center shadow-md">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    </div>
                    <p className="text-sm font-bold text-slate-700 uppercase tracking-wide">Sent</p>
                  </div>
                </div>
              </div>

              <button
                onClick={() => window.location.reload()}
                className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 px-10 rounded-md shadow-xl hover:shadow-2xl transition-all duration-200 uppercase tracking-wide"
              >
                <div className="flex items-center gap-2">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                  </svg>
                  Return to Home
                </div>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
